feat(#55): tutorial step 2
phox081/docs-it pull request #89
Opened 2023-08-31 18:27 UTC by AlessioChen

## Description of Problem

## Proposed Solution

## Additional Information

2023-09-06 21:32 UTC, phox081 requested changes
ci sono delle modifiche riguardo ad esempio mustaches syntax usato in più punti che va tradotto con sintassi mustache, e qualche typo, per il resto tutto ok.

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Quello che si vede nell'editor è un Vue Single-File Component (SFC). Un SFC è un blocco di codice autonomo e riutilizzabile che incapsula HTML, CSS e Javascript tutto in un unico file `.vue`.
Vue Single-File Component -> Componente Single-File (SFC) di Vue

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +La caratteristica principale di Vue è il **rendering dichiarativo**. Utilizzando una sintassi di template che estende l'HTML, possiamo descrivere come deve apparire l'HTML in base allo stato di Javas
possiamo descrivere come deve apparire -> possiamo descrivere come dovrebbe apparire

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Uno stato che può attivare aggiornamenti quando viene modificato è considerato **reattivo**. Possiamo dichiarare uno stato reattivo usando l'API `reactive()` di Vue. Gli oggetti creati da `reactive()
può attivare aggiornamenti -> può attivare degli aggiornamenti

sono [Proxies] -> manca Javascript, lo aggiungerei dopo il link ->
sono [Proxies] (..) JavaScript

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +`reactive()` funziona solo sugli oggetti (compresi gli array e i tipi nativi come `Map` e `Set`). `Ref`, invece può prendere qualsiasi tipo di valore e creare un oggetto che espone il suo valore inte
`Ref`, invece -> `Ref`, invece,

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Dettagli su `reactive()` e `ref()` sono discussi in <a target="_blank" href="/guide/essentials/reactivity-fundamentals.html">Guide - Le basi della Reattività</a>.
Guide - Le basi -> Guida - Le basi

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Lo stato reattivo dichiarato nel blocco `<script setup>` del componente può essere usato direttamente nel template. Ecco come possiamo rendere un testo dinamico basato sul valore dell'oggetto `counte
usando la sintassi dei baffi: -> usando la sintassi mustache:

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Le proprietà che restituisce l'oggetto saranno rese disponibili nel template. Questo è il modo in cui possiamo rendere un testo dinamico basato sul valore `message`, usando la sintassi dei baffi:
Le proprietà che restituisce l'oggetto ->
Le proprietà restituite dall'oggetto

Questo è il modo in cui possiamo rendere un testo dinamico basato sul valore `message`, usando la sintassi dei baffi: 
->
Ecco come possiamo rendere dinamico un testo basato sul valore  di `message`, usando la sintassi mustache:

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +<p>valore di count: {{ counter.count }}</p>
in altri punti della guida, lo stesso esempio con  count è stato tradotto con: conteggio , possibilmente usiamo conteggio

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Si noti come non sia necessario usare `.value` quando si accede al ref `message` nei templates: viene automaticamente decompresso per un uso più sintetico.
unwrapped = estratto
: decompresso -> estratto

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Ora, prova a creare tu una proprietà reattiva e utilizzala come contenuto testuale per `<h1>` nel template.
Ora, prova a creare tu una proprietà reattiva -> 
Ora, prova a creare tu una proprietà del data reattiva

del data potrebbe andare anche tra parentesi tonde 
Ora, prova a creare tu una proprietà (del data) reattiva

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Il contenuto all'interno dei baffi non è limitato a identificatori o paths - possiamo usare qualsiasi espressione Javascript valida:
Il contenuto all'interno dei baffi ->
Il contenuto all'interno delle parentesi graffe (sintassi mustache)

2023-09-06 21:32 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +La proprietà `message` sarà resa disponibile nel template. Ecco come possiamo rendere il testo dinamico in base al valore di `message`, usando la sintassi dei baffi:
sintassi mustache (valore che si ripete, vedi altre note, cerca e sostituisci)

2023-09-06 21:46 UTC, AlessioChen commented on src/tutorial/src/step-2/description.md
> +Ora, prova a creare tu una proprietà reattiva e utilizzala come contenuto testuale per `<h1>` nel template.
del data -> all'interno di data ? è meglio

2023-09-06 21:51 UTC, AlessioChen commented on src/tutorial/src/step-2/App/composition.js
> +      // esposto al template
Second me vanno bene entrambi non c'è una differenza così grande.

2023-09-08 16:02 UTC, phox081 commented on src/tutorial/src/step-2/description.md
> +Ora, prova a creare tu una proprietà reattiva e utilizzala come contenuto testuale per `<h1>` nel template.
@AlessioChen quando riesci a fare la modifica taggami che mergiamo asap

2023-09-08 16:03 UTC, phox081 approved these changes

2023-09-08 16:04 UTC, merged

2023-09-08 16:09 UTC, AlessioChen commented on src/tutorial/src/step-2/description.md
> +Ora, prova a creare tu una proprietà reattiva e utilizzala come contenuto testuale per `<h1>` nel template.
@phox081 è già fatto